JITx-Inc/jsl

- examples/protocols/common/example-board.stanza
- examples/protocols/common/example-components.stanza
- examples/protocols/displayport/README.md
- examples/protocols/displayport/displayport-board.stanza
- examples/protocols/displayport/displayport-main.stanza
- examples/protocols/displayport/displayport-src.stanza
- examples/protocols/pcie/README.md
- examples/protocols/pcie/pcie-board.stanza
- examples/protocols/pcie/pcie-src.stanza
- src/protocols/displayport.stanza
- src/si/couplers.stanza
- src/si/helpers.stanza
Will add example code although it should be simple...
> added first pass of DP bundle and helpers

- src/landpatterns/SON.stanza
- stanza.proj
- tests/landpatterns/SON.stanza
This supports the components in the USB C converter design.
> Added SON package land pattern generator

- src/si/helpers.stanza
This allows for setting the constraints on multiple KeyValue pairs at a time with no loss of functionality.
> Updated SI helpers to include a variadic arg

- examples/protocols/common/example-board.stanza
- examples/protocols/displayport/displayport-main.stanza
- examples/protocols/pcie/pcie-main.stanza
Leverage more of the API for the protocols.
> Updated the diff-impedance for the examples to be parametric.

- examples/symbols/resistor.stanza
This was an erroneous path from by @bhusang
> [Bugfix] Updated path for package

- src/geometry/box.stanza
- src/landpatterns/BGA/pads.stanza
- src/landpatterns/BGA/planner.stanza
This updates the BGA pad functions to work for arbitrary shapes.
> Updates to the BGA pad

- src/layerstack.stanza
- tests/layerstack.stanza
> remove validate! function

- src/protocols/ethernet/MII/MIIM.stanza
Adds missing interface for the management MDC/MDIO that got lost in the ethernet refactor.
> Added the MIIM management interface for ethernet.

- src/layerstack.stanza
- tests/layerstack.stanza
I tried to explore different methods to create LayerStack.
Check out 
- deftest(layerstack) make-layer-stack-method1 :
- deftest(layerstack) make-layer-stack-method2 :
- deftest(layerstack) make-layer-stack-method3 :
- deftest(layerstack) make-layer-stack-method4 :
> JSL/make-layer-stack: explore different methods to create LayerStack

- src/landpatterns/BGA/package.stanza
- src/protocols/ethernet.stanza
- src/protocols/ethernet/MDI/MDI-1000Base-T.stanza
1.  Adds a new generator for the 1000Base-T Supports 
2.  Adds a forwarding package for the ethernet protocols
> Updates to ethernet packages

- src/bundles/comms.stanza
Note that this implements a standard bundle for the receiver and transmitter.
> Added the `I2S` protocol bundle specification

- src/landpatterns/numbering.stanza
- tests/landpatterns/numbering.stanza
Adds `row-offset` and `col-offset` optional parameters for Row and Column major numbering types. 
I've added tests that show the behavior of each.
> Added offset parameters for Row and Column Major Numbering.

- src/landpatterns/VirtualLP.stanza
- src/protocols/ethernet/MDI/MDI-1000Base-T.stanza
- add helper in make-1000T
- add VirtualCutouts to VirtualLP
> JITX-8858: add support functions to JSL for ethernet connector

- src/landpatterns/BGA/package.stanza
- src/landpatterns/QFN.stanza
- src/landpatterns/SOIC.stanza
- src/landpatterns/SON.stanza
- src/symbols/DIAC.stanza
- src/symbols/SCR.stanza
- src/symbols/TRIAC.stanza
- src/symbols/audio.stanza
- src/symbols/box-symbol.stanza
- src/symbols/capacitors.stanza
- src/symbols/comparator.stanza
- src/symbols/diode-bridge.stanza
- src/symbols/diodes.stanza
- src/symbols/inductors.stanza
- src/symbols/instrumentation-amp.stanza
- src/symbols/logic/AND.stanza
- src/symbols/logic/OR.stanza
- src/symbols/logic/buffer.stanza
- src/symbols/op-amps.stanza
- src/symbols/potentiometer.stanza
- src/symbols/resistors.stanza
- src/symbols/transformer.stanza
- src/symbols/transistors/BJT.stanza
- src/symbols/transistors/FET.stanza
- src/symbols/transistors/JFET.stanza
Attempt at reducing complexity
> Import Refactors

- examples/symbols/box-symbol.stanza
Unfortunately, this code can't really integrate into the unit tests. I've moved it into the examples.
> Moved the box symbol test to the examples folder.

- src/landpatterns/courtyard.stanza
This addresses the JSL short coming of this:
https://linear.app/jitx/issue/PROD-377/courtyard-outline-undocumented-behavior
> Convert Courtyard LineRectangle to Rectangle to make more sane

- .github/docker-compose.yml
- .github/jitx-client/Dockerfile
- .github/jitx-client/user.params
- .github/workflows/test.yml
- Makefile
- **Add .github actions tests**
- **Bump CI**
- **Bump CI**
> Test PR to ghci branch to trigger gh actions"

- src/landpatterns/leads.stanza
- src/landpatterns/leads/lead-types.stanza
- src/landpatterns/leads/through-hole.stanza
- src/landpatterns/two-pin/axial.stanza
- src/landpatterns/two-pin/radial.stanza
- src/landpatterns/two-pin/utils.stanza
This supports the [grid generator PR](https://github.com/JITx-Inc/jsl/pull/108).
I'm trying to break these up into smaller pieces.
> Through-Hole Pad Overrides

- examples/landpatterns/QFP.stanza
- src/geometry/box.stanza
- src/landpatterns/QFP.stanza
- src/landpatterns/generators.stanza
For use with STM microcontroller library.
This will need some work -- I basically just copy-pasted from QFN. Opening a PR so that somebody more qualified can fix it up.
> Flesh out QFP

- examples/landpatterns/board.stanza
- examples/protocols/common/example-board.stanza
- examples/protocols/displayport/displayport-main.stanza
- examples/protocols/displayport/displayport-src.stanza
- examples/protocols/sata/SATA-src.stanza
- src/bundles/comms.stanza
- src/bundles/debug.stanza
- src/bundles/gates.stanza
- src/bundles/general.stanza
- src/circuits/ConfigStrap.stanza
- src/layerstack.stanza
- src/pin-assignment/generators.stanza
- src/protocols/displayport.stanza
- src/protocols/ethernet/MII/GMII.stanza
- src/protocols/ethernet/MII/MII.stanza
- src/protocols/ethernet/MII/MIIM.stanza
- src/protocols/ethernet/MII/RGMII.stanza
- src/protocols/ethernet/MII/RMII.stanza
- src/protocols/pcie.stanza
- src/protocols/usb.stanza
- src/si/couplers.stanza
- src/symbols/SymbolNode.stanza
- src/via-structures.stanza
- tests/pin-assignment.stanza
- tests/si/signal-ends.stanza
This PR includes work from both me and @bhusang to update the code with the reformed syntax that should land in `3.14` ( 🤞 )
This should be the common place where to handle all syntax reforms. If subsequent PRs create or edit those lines - we should modify them here so that we can fix everything with one single PR. 
This PR must NOT merge until 3.14 is released.
> Syntax Reforms PR (merge after 3.14 is released)

- src/protocols/displayport.stanza
- src/protocols/ethernet/MDI/MDI-1000Base-T.stanza
- src/protocols/ethernet/MDI/MDI-100Base-TX.stanza
- src/protocols/ethernet/MDI/e10GBASE-KR.stanza
- src/protocols/pcie.stanza
- src/protocols/sata.stanza
- src/protocols/usb.stanza
- src/si/constraints.stanza
> Rename DP-Constraint => DiffPair-Constraint

- src/landpatterns/thermal-vias.stanza
I merged the last PR too quickly. I forgot to accomodate for the change to `PortInfo`
> [Bugfix] Fixed issue introduced by `PortInfo` change.

- src/circuits/CrystalResonator.stanza
This commit adds a new circuit generator for supporting crystal oscillators.
> Added crystal resonator circuit

- examples/landpatterns/Molded-2pin.stanza
- src/landpatterns/silkscreen.stanza
- src/landpatterns/two-pin/axial.stanza
- src/landpatterns/two-pin/generators.stanza
- src/landpatterns/two-pin/molded.stanza
- src/landpatterns/two-pin/radial.stanza
- src/symbols/capacitors.stanza
> Added Molded 2-pin Component Land Pattern

- src/bundles/comms.stanza
@alijitx  - I've added this because it seems to be pretty common approach both in stmicro, FTDI, etc.
> Added UART with flow control (RTS/CTS) bundle

- src/circuits/utils.stanza
Converts `bypass` to use `JITXObject` instead of `Instance`.
Added a tool for pullups.
> Updated `bypass` to use JITXObject and added `add-pullup`

- src/landpatterns/leads/lead-types.stanza
> Make `Lead` abstract

- Makefile
- update makefile to include box symbol tests
> Add BoxSymbol tests to JSL tests

- slm.toml
- src/design/Substrate.stanza
Remove backdrill filter to relieve API issues in 3.21
> [Refactor] Remove the backdrill until API stabilizes

- slm.toml
- src/bundles/comms.stanza
- src/layerstack.stanza
This was preventing the build of the docs site.
> Fix microwire docs

- slm.toml
Updated release for the default query generators
> [Bump] increment version to 0.9.6

- src/layerstack.stanza
I discovered when testing in SiWave that our defaults were causing issues.
> Updated the FR4 default loss tangents

- src/landpatterns/dual-row.stanza
- src/landpatterns/leads/lead-profile.stanza
- src/landpatterns/leads/lead-types.stanza
- src/landpatterns/pad-planner.stanza
- src/si/pairs.stanza
Addresses issue that was causing the documentation build to fail. 
Other minor updates.
> Misc updates and Docs Fix

- src/protocols/memory/ddr4.stanza
To support Cisco's memory widths
> adding x24 and x40
