- src/design/settings.stanza
This was referencing a `ocdb` path that was in conflict when attempting to use both JSL and OCDB in the same project. This retargets the `pcb-enum` path.
> [Bugfix] Fixed improper path in `pcb-enum`

- src/symbols/box-symbol.stanza
- tests/designs/BoxSymbolTest.stanza
- add minimum grid chunk to account for spacing between box and pin name when calculating total width
before: 
after:
> JITX-8584: improve spacing between pin names on opposite sides of box symbol

- examples/landpatterns/BGA-thermal-enhanced.stanza
Currently working on diagrams for the JSL documentation and needed an example for this:
> Added example for the thermally enhanced BGA pattern

- examples/landpatterns/SON.stanza
- src/landpatterns/BGA/package.stanza
- src/landpatterns/QFN.stanza
- src/landpatterns/SOIC.stanza
- src/landpatterns/SON.stanza
- src/landpatterns/VirtualLP.stanza
- src/landpatterns/dual-row.stanza
- src/landpatterns/headers.stanza
- src/landpatterns/two-pin/SMT.stanza
- src/landpatterns/two-pin/radial.stanza
This adds a new feature to generate an initial reference designator placement in landpattern generators. 
I've added an example for the SON package. 
I've added some refactors to reduce code duplication.
Examples should now show this:
With a U1 or similar ref-des
> Add Reference Designators for Package Generators

- src/landpatterns/numbering.stanza
- tests/landpatterns/numbering.stanza
In some packages, particularly BGAs composed of pad matrices with differing pitches, the grid may need to skip some column numbers. This is a similar but simpler problem to the omitted row letters.
This adds the ability for the user to pass a column omit list so that the grid numbering will skip some columns when necessary.
> Added column omits for the grid numbering

- src/layerstack.stanza
- tests/layerstack.stanza
Support access functions for Layerstack:
- get layer by index function:  `test-stack[0]`
- get conductor layer by index: `conductors(test-stack)[0]`
- set-name function: `set-name(test-stack[0] One("cu3-new"))`
- set function to change a layer by index: `test-stack[0] = new-stack`
- allow arguments of `Copper()` functions to be either weight or thickness.
I created the ticket PROD-132 for this issue, but forgot to include it in the branch name.
> PROD-132/Jsl/layerstack access functions

- src/bundles.stanza
Fixes bug introduced by #63 
The use of `forward` declarations unfortunately is a bit error prone when developing libraries like this. The unit tests did not detect this for some reason. I'm not sure why.
> [Bugfix] Removed `displays.stanza` but didn't remove from forwards

- examples/protocols/ethernet/RGMII_1000BaseT/main.stanza
Latest release fixes issues with use of `reverse-lane`. Updated to add pin models
I've added swappable diff-pair on the PHY to make this easier to demonstrate the routing.
This is primarily to make it easier for me to write docs related to the `timing-difference` constraints.
> Updated the 1000BaseT example

- src/protocols/ethernet/MII/RGMII.stanza
I had this backwards and it was push a 2.5ns delay on `ctl` instead of on `clk`.
> [Bugfix] Fixed delay constraint on `ctl => clk`

- examples/protocols/common/example-board.stanza
- examples/via-structures/diff-via-structure.stanza
- examples/via-structures/se-via-structure.stanza
- src/geometry/NotchedShapes.stanza
- src/via-structures.stanza
- stanza.proj
- tests/geometry.stanza
- tests/via-structures.stanza
This PR adds a new framework for constructing via structures using `pcb-module` with `geom/via/layer` statements. 
Here are some examples: 
Single Ended Via Structure with a Double Chipped Circle Antipad and 4 ground cage vias: 
Diff-Pair Via Structure with a Double Notched Rectangle Antipad and 6 ground cage vias: 
Hard to see the double notch anti-pad - here is the keepout region turned on: 
1.  The `CustomLayer` content was not showing in the layer stack - so I put the insertion points on the silkscreen just so they would show. Probably want to revert that in the future.
2. I can't create a courtyard by introspection. There isn't really a way for me to introspect the via locations in a module. Or at least, I haven't found one. If you know of a way - let me know.
3.  The forbid copper …
> Added initial Via Structures Framework

- src/landpatterns/BGA/package.stanza
- src/landpatterns/BGA/planner.stanza
- src/landpatterns/VirtualLP.stanza
Adds a corner cut matrix planner for the BGA landpattern generation. Fixes a bug where the BGA silkscreen generation would crash if no A[1] pad exists by selecting the lowest-numbered alternative pad as the substitute.
> Corner cut BGA

- src/circuits/ConfigStrap.stanza
- src/design/ConfigStrap.stanza
- src/design/introspection.stanza
- src/landpatterns/courtyard.stanza
- src/landpatterns/framework.stanza
- src/landpatterns/introspection.stanza
- src/si/couplers.stanza
This adds a new module that will array a set of components for a configuration strap array.
https://github.com/JITx-Inc/jsl/assets/622392/7a92b104-c964-407b-8996-98d6068eeddc
It works for through-hole and surface mounts and handles figuring out how to best orientate the components when placing them. 
Then you can use pin assignment to generate the best connections.
> Add a configuration strap component array generator

- src/symbols/box-symbol.stanza
- src/symbols/box-symbol/utils.stanza
This package has been removed in the latest `jitx-client` on `develop`. It causes JSL to break. I'm removing it here. I've tested the BoxSymbol implementation and it does not seem to suffer (still compiles, still runs).
> Removed ref to JITX package removed in latest `jitx-client` build

- src/bundles/general.stanza
- src/pin-assignment/generators.stanza
Renames the member pin names for the general bundles to distinct names instead of 'p' to ensure the bundles cannot be aliased to each other.
> Bundle pin rename

- src/landpatterns/packages.stanza
This adds a default implementation that does nothing because most implementations won't require this.
> Added the cutout interface for the `Package` type.

- examples/symbols/net-symbols.stanza
- src/symbols/net-symbols.stanza
- src/symbols/net-symbols/bar-ground.stanza
- src/symbols/net-symbols/bar-power.stanza
- src/symbols/net-symbols/framework.stanza
- src/symbols/net-symbols/ground-symbol.stanza
- src/symbols/net-symbols/power-symbol.stanza
- src/symbols/net-symbols/symbol-builder.stanza
This implements a new framework for constructing parametrically generated net symbols.
Example:
> Add the NetSymbol framework

- examples/protocols/pcie/pcie-src.stanza
- src/protocols/displayport.stanza
- src/protocols/pcie.stanza
- src/protocols/sata.stanza
This PR is just to use of lane-pair in the PCIe code instead of explicit separate RX/TX.
> Use lane-pair for PCIe

- src/symbols/box-symbol.stanza
- tests/symbols/box-symbol.stanza
Property check was broken as the value of wildcard type was not properly accessed for comparison.
> PROD-313: Fix property checking in BoxSymbolv2

- src/layerstack.stanza
- tests/layerstack.stanza
Revert the last commit after Carl's approval of v1.
That last commit has the following changes:
- enhanced `make-layer-stack` to support multiple adjacent dieletric layers like `[copper [prepreg1 prepreg2]]`, which is found in many JLC-PCB stackup.
- Specific references to JLC-PCB stackups like jlcpcb-2313 was removed so the examples are general
These changes are reverted.
> revert the last commit after Carl's approval of v1

- src/design/introspection.stanza
- stanza.proj
- tests/design/introspection.stanza
This adds a function for checking if a 2-pin component is the `p[1]/p[2]` version or the `c/a` version and returning the pins in a known order.
> Added methods to support pin extraction for 2-pin devices

- src/landpatterns/BGA/package.stanza
- src/landpatterns/QFN.stanza
- src/landpatterns/SOIC.stanza
- src/landpatterns/SON.stanza
- src/landpatterns/VirtualLP.stanza
- src/landpatterns/dual-row.stanza
- src/landpatterns/packages.stanza
- src/landpatterns/silkscreen.stanza
- tests/landpatterns/VirtualLP.stanza
1.  Support `build-all` overrides better
2.  Tools for easier child node lookup by name
3.  Bugfix for `get-pads` that fixes the courtyard outline for LPs with multiple child nodes
4.  Added silkscreen from package body helper routine.
> Virtual LP FIxups to Support ethernet connector

- examples/via-structures/se-via-structure.stanza
- src/via-structures.stanza
I had mistakenly thought that the `Bottom` wasn't usable because I didn't know the size of the board from the code. But `ForbidCopper` has an interface that allows it. I've removed the checks and I'm just using that directly.
> [Bugfix] Fixed the antipad not allowing `Bottom` as the side.

- src/landpatterns/BGA/pads.stanza
This bug was introduced in:
https://github.com/JITx-Inc/jsl/pull/61
This was a minor issue in the way that percentage modifications of the pad size were applied.
Unit tests pass when I run them locally.
> [Bugfix] Fixed regression in the BGA pad generator

- src/symbols/box-symbol.stanza
- tests/symbols/box-symbol.stanza
Improve exception messages when there are pins with and without `bank` property
> PROD-250: Better error reporting for symbols with banked and unbanked

- src/landpatterns/courtyard.stanza
- src/landpatterns/packages.stanza
- tests/landpatterns/courtyard.stanza
Previously if you made a very small component - like an 0201 - then you would get an origin marker that was too large: 
With this PR - the marker gets scaled if it would be larger than some ratio of the minimum(width/height) of the courtyard: 
This allows the functions that rely on the courtyard to accurate compute the distance between components. 
I also fixed a test regression and added a test for this origin builder in the scene graph.
> Create courtyard origins with variable size

- examples/protocols/common/example-board.stanza
- examples/protocols/displayport/displayport-main.stanza
- examples/protocols/displayport/displayport-src.stanza
- src/protocols/displayport.stanza
I can route - but the Aux diff-pair isn't getting a routing structure. Probably related to `symmetric-shunt` somehow. 
I'm not sure why we lost the package level docstring on display port.
> Display Port Updates to work with SI-Constraint

- examples/landpatterns/BGA-Stagger.stanza
- examples/landpatterns/BGA-complex.stanza
- examples/landpatterns/BGA-simple.stanza
- examples/landpatterns/BGA-thermal-enhanced.stanza
- examples/landpatterns/headers.stanza
- examples/pin-assignment/swizzle.stanza
- src/landpatterns/BGA/package.stanza
- src/landpatterns/BGA/planner.stanza
- src/landpatterns/VirtualLP.stanza
- src/landpatterns/dual-row.stanza
- src/landpatterns/framework.stanza
- src/landpatterns/grid-planner.stanza
- src/landpatterns/headers.stanza
- src/landpatterns/numbering.stanza
- src/landpatterns/pad-grid.stanza
- src/landpatterns/pad-planner.stanza
- src/landpatterns/quad.stanza
- src/landpatterns/two-pin/utils.stanza
- tests/landpatterns/BGA/package.stanza
- tests/landpatterns/BGA/planner.stanza
- tests/landpatterns/pad-planner.stanza
The goal is to:
1.  Reduce duplication in the grid generation. 
2.  Add routines that can support the ethernet connector generator.
This also includes several bugfixes. 
Unit tests pass when I run them locally.
1.  This changes the `BGA` interface to put the `rows/columns` management into the BGA Planner instead of on the BGA itself.
1.  This seems to jive well with the Corner Cut planner from @alijitx 
2.  I've updated dual-row and quad to use GridPlanner for their construction mechanism.
1.  This works well for both.
2.  But the helper function only works for the dual not the quad, because of the two separate lead-profile mechanisms the quad supports.
3.  I've updated the headers functionality to use this pad grid concept and added examples of using the headers.
1.  We need better …
> Add a new Grid management facility for landpattern generation

- src/si/physics.stanza
This is convenience update as found by @lchao-jitx . 
The interface for the transmission lines was already assuming mm / s so I think this was just a bug / oversight.
> Converts physics functions to use `mm` instead of `m`

- examples/symbols/ferrite.stanza
- src/symbols/ferrite.stanza
- src/symbols/generators.stanza
This adds a new schematic symbol for the ferrite component:
> Added ferrite schematic symbol

- src/landpatterns/courtyard.stanza
- tests/landpatterns/BGA/package.stanza
- tests/landpatterns/SOIC.stanza
- tests/landpatterns/courtyard.stanza
Closes PROD-413
This is required because KICAD won't allow other shapes than the boundary shape on the courtyard layer.
This will allow export to complete successfully.
> [Bugfix] Move courtyard origin to a custom layer.

- src/symbols/ferrite.stanza
This was causing ambiguous symbol errors in some of the examples.
> [Bugfix] Renamed field in Ferrite Symbol Params

- src/design/introspection.stanza
Closes PROD-419
Adds some tools for getting the pad or pads associated with a particular port a component. This will help with extracting pad shapes for generating thermal via patterns. 
Thanks @ariel-hi  - I think this path is going to work well.
> Add introspection utilities for port -> pad mappings.

- examples/protocols/pcie/pcie-main.stanza
- examples/protocols/pcie/pcie-src.stanza
- src/protocols/pcie.stanza
I've update the PCIe protocol and example to use the `SI-Constraint` model.
Here is the straight through version (ie IC to connector):
Notice the blocking caps on only the TX side. 
Here is the null-modem case (ie, IC to IC, TX => RX, RX => TX):
Blocking caps on both TX channels. Notice that the routing structure application is not working for the null-modem case because of the use of `node` in `reverse-pcie-lanes`.
> Refactor PCIe to use the `SI-Constraint` model

- examples/protocols/common/example-board.stanza
This somehow got reverted in the process of applying the updated syntax changes.
> Updated se-50 with `layer-constraints` syntax

- examples/symbols/crystal.stanza
- src/symbols/crystal.stanza
- src/symbols/generators.stanza
Adds a new schematic symbol:
There are two modes - one with a case and one without. Also has optional case pads for grounding the case.
> Added crystal component symbol and an example

- src/landpatterns/numbering.stanza
This helps will parts like the EPSON FA-238 crystal series where the pad numbering doesn't really match standard patterns.
> Added a new lookup table based numbering scheme.

- examples/landpatterns/SOT.stanza
- src/geometry/box.stanza
- src/landpatterns/SON.stanza
- src/landpatterns/SOT.stanza
- src/landpatterns/generators.stanza
Adds the SOT-23-6, SOT-23-8, SOT-23-5, and SOT-23-3 default implementations.
> Add SOT land pattern packages

- tests/utils.stanza
The latest develop makes a change to `set-default-rules` that seems to break the tests. By changing it to `set-rules` - I can resolve these problems and the tests pass.
> Update to resolve failing unit tests in develop

- examples/landpatterns/SOT.stanza
- src/landpatterns/SOT.stanza
- src/landpatterns/dual-row.stanza
- src/landpatterns/leads/lead-types.stanza
- src/landpatterns/quad.stanza
- tests/landpatterns/QFN.stanza
Fixed a bug in the quad and dual package that was causing the leads not to be generated with respect to the passed density level.
> Add SOT Flat Lead type and fix bugs.

- src/design/introspection.stanza
- src/errors.stanza
- src/landpatterns/introspection.stanza
- tests/design/introspection.stanza
This adds features for accessing components and pads from ports. I've refined the existing `get-pads-from-port` so that we don't need to pass an argument anymore.
I've achieved this by creating a `get-component-from-port` which can get the component instance associated with a port. We can then create the pad mapping from that component.
I've added some unit tests for the functionality to confirm that works as expected.
> Added more introspection of components, modules, and ports

- src/landpatterns/thermal-vias.stanza
This provides the base implementation for supporting thermal via grids in components programmatically. The current implementation does not use the `via` introspection as that isn't available yet. Additionally, this is dependent on some of the introspection tools provided in `cja/more_introspection`. 
The base implementation we will expand as the `via` introspection and other fixes get released.
We will likely need to wait until at least 3.15 for that.
> Added thermal via grid generator

- Makefile
- examples/landpatterns/Molded-2pin.stanza
- examples/symbols/capacitor.stanza
- examples/symbols/diode.stanza
- src/circuits/Network.stanza
- src/ensure.stanza
- src/symbols/DIAC.stanza
- src/symbols/TwoPinSymbol.stanza
- src/symbols/capacitors.stanza
- src/symbols/crystal.stanza
- src/symbols/diodes.stanza
- src/symbols/ferrite.stanza
- src/symbols/inductors.stanza
- src/symbols/potentiometer.stanza
- src/symbols/resistors.stanza
- tests/circuits/Network.stanza
Tool for constructing series, parallel, and other lumped circuit networks.
```
val circ = create-circuit( R1 + Tap(R2, `divOut)) 
```
Creates an instantiable for a resistive divider with a central tap port `divOut` and endpoint ports `p[1]` and `p[2]` like a standard two-pin component. For example:
```
pcb-module representative-circuit:
port p : pin[[1, 2]]
port divOut 
inst r1 : R1 
inst r2 : R2 
net (r1.p[1], p[1[)
net( r1.p[2], r2.p[1], divOut)
net( r2.p[2], p[2] )
```
This is a simple example - but more complex circuits with `Parallel` and `ShuntTo` are possible.
> Add Circuit Network Generator

- src/symbols/inductors.stanza
Sometimes inductors have a pin 1 marker and it is helpful to use a polarized variant for these.
> [Bugfix] Updated inductor symbol constructor to allow polarized argument

- examples/symbols/SCR.stanza
- src/symbols/SCR.stanza
- src/symbols/diode-bridge.stanza
- src/symbols/diodes.stanza
The change to add `polarized?` to the `TwoPinSymbol` base class put the `a` (anode) in the +Y and the `c` (cathode) in -Y. The Diode symbols were unfortunately written with `c` in +Y and `a` in -Y.
This flips them so that the cathode is in the -Y half-plane
I've also fixed the diode bridge and SCR which also use this functionality.
The new symbols now look like this:
Notice that the cathode is in the -Y half-plane
> [Bugfix] Fixed Diode A/C backwards issue

- src/landpatterns/two-pin/molded.stanza
This allows different pin 1 marker configurations depending on what pin we want to mark. For example - diodes we want to mark the cathode:
For inductors and capacitors, we might want to mark the anode:
> Updated the `molded` landpattern to have configurable pin-1 marker

- src/landpatterns/pad-planner.stanza
This allows for generating staggered pad patterns like this:
We had one for through-hole but this adds one for SMT
> Added a stagger pad planner for SMT

- examples/symbols/switches.stanza
- src/symbols/generators.stanza
- src/symbols/switches.stanza
This is a starting point. Ideally, we would also have SPDT and other implementations.
> Added schematic symbols for momentary and toggle switches

- src/pin-assignment/generators.stanza
I found that I was doing a lot of duplicate
`require` statements, especially in microcontrollers.
This function allows the user to define a port of a particular type and then use introspection to determine which kind of require port to create.
```
port switch-irq-n
port switch-pme-n
port dbg : jtag
port acm : uart-fc()
port boot-ctl
port dbg-active
public inst mcu : stmicro/components/STM32H723VGT6/module
connect-require-ports(mcu, [dbg, acm, reset-n], def-bundle = reset)
connect-require-ports(mcu, [switch-pme-n, switch-irq-n, dbg-active])
```
This constructs: 
1.  A `uart-fc()` require port
2.  A `jtag` require port
3.  A `reset` require port
4.  3 `gpio` require ports
> Added a new tool for connecting to `require` ports

- examples/protocols/common/example-components.stanza
I spot checked and it seems like the issue is only in the via structures and protocols examples. Basically anywhere we use the `block-cap` or `pu-res` components.
> Added `jitx/emodels` to fix broken examples

- slm.toml
- src/circuits/Bypass.stanza
- src/circuits/Pullups.stanza
- src/circuits/utils.stanza
For example: 
```
val fine-C = create-capacitor(
bypass-query,
capacitance = 0.1e-6,
rated-voltage = Interval(max-rail-V, max-voltage)
)
for p in pins(C.VDDIO) do:
net (p, rail-IO.V+)
val c = insert-bypass(p, GND, elem-type = fine-C)
schematic-group(c) = bypass-cap-IO
```
```
insert-pullup(ROM.C.CS, VDD-3v3)
insert-pullup(ROM.C.CLK, VDD-3v3)
insert-pullup(ROM.C.DO, VDD-3v3)
```
This functions work with both nets, SinglePin ports, and `power` bundle ports. 
-------
I've added `maybe-utils` as a dependency. I think it could help reduce complexity in some of the code.
> Add Bypass and Pullup Tools

- src/design/introspection.stanza
The previous functions worked for instances but
the SchematicSymbol is a definition and so I needed to add some additional handling to support this.
> [Refactor] Added schematic symbol port introspection

- src/symbols/switches.stanza
This was causing the DIP switch array components to not build correctly.
> Added missing pin-refs argument for switch constructors

- examples/landpatterns/QFN.stanza
- examples/landpatterns/SOP.stanza
- src/landpatterns/QFN.stanza
- src/landpatterns/QFP.stanza
- src/landpatterns/SOIC.stanza
- src/landpatterns/SON.stanza
- src/landpatterns/SOP.stanza
- src/landpatterns/SOT.stanza
- src/landpatterns/VirtualLP.stanza
- src/landpatterns/dual-row.stanza
- src/landpatterns/framework.stanza
- src/landpatterns/pads.stanza
- src/landpatterns/quad.stanza
- src/landpatterns/thermal-pads.stanza
This adds a new generator implementation allows for the paste application to be subdivided: 
It is a little hard to see - but the faint white squares in the thermal pad are where I'm subdividing the paste mask.
The generator is fully generalized and uses the same `PadPlanner` and `GridPlanner` implementations for the pad construction. 
This is also the place where we can add custom soldermask pattern handling in the future.
> Added a thermal pad generator with paste subdivision

- src/landpatterns/introspection.stanza
- src/landpatterns/leads.stanza
- tests/design/introspection.stanza
- tests/landpatterns/BGA/package.stanza
- tests/landpatterns/BGA/pads.stanza
- tests/landpatterns/QFN.stanza
- tests/landpatterns/SOIC.stanza
- tests/landpatterns/SON.stanza
- tests/landpatterns/courtyard.stanza
- tests/landpatterns/two-pin/SMT.stanza
- tests/landpatterns/two-pin/axial.stanza
- tests/landpatterns/two-pin/radial.stanza
Replace pad with pad-def as part of deprecation process (jitx-client PR 4759)
> replace pad with pad-def

- src/design/introspection.stanza
- src/landpatterns/thermal-vias.stanza
Eventually we will probably delete this, for now I:
* added an introspection `get-connected-nets` that returns all connected net statements
* changed `make-via-grid` to just net directly to the target object
* changed the corresponding field in `PortInfo` to a tuple
* added a function `connected-net` on `PortInfo` that mimics the old functionality (for backwards compatibility)
Another thing we will need to look at:
`make-thermal-vias` assumes the existence of a single `net` statement for its `geom` statement. This will often not be true -- it still works since I reimplemented `connected-net`, but it will arbitrarily select the first net statement. Maybe this is fine, I'm not 100% sure
> Phase out `get-connected-net`

- examples/protocols/displayport/displayport-src.stanza
- examples/protocols/pcie/pcie-src.stanza
- examples/symbols/box-symbol.stanza
* use `min-col-width` and `min-row-width` to make these examples runnable.
> use min-col-width and min-row-width

- examples/landpatterns/SMT.stanza
- src/landpatterns/BGA/package.stanza
- src/landpatterns/QFP.stanza
- src/landpatterns/SOIC.stanza
- src/landpatterns/SON.stanza
- src/landpatterns/SOP.stanza
- src/landpatterns/SOT.stanza
- src/landpatterns/VirtualLP.stanza
- src/landpatterns/quad.stanza
- src/landpatterns/silkscreen.stanza
- src/landpatterns/two-pin/SMT.stanza
- src/landpatterns/two-pin/axial.stanza
- src/landpatterns/two-pin/molded.stanza
- src/landpatterns/two-pin/radial.stanza
I'm trying to setup a framework by which we can allow customization of silkscreen content including the outline, pin1 markers, etc. 
This PR adds a interface type for silkscreen outlines and then converts existing code to create multiple different implementations of that interface.
This allows me to consolidate some code as well as set up a future where the silkscreen outline is an argument to the package. 
I've also added a better silkscreen for the SMTs that uses two lines instead of the full line rectangle:
It doesn't look great for small case sizes like 0402 and 0201 - we will improve those.
> Updates to the Silkscreen Generation

- examples/landpatterns/SMT.stanza
- src/ensure.stanza
- src/landpatterns/VirtualLP.stanza
- src/landpatterns/framework.stanza
- src/landpatterns/keep-outs.stanza
- src/landpatterns/silkscreen.stanza
- src/landpatterns/two-pin/SMT.stanza
- src/landpatterns/two-pin/molded.stanza
- tests/landpatterns/two-pin/SMT.stanza
This provides a mechanism for customizing the keep out generators for components, specifically SMT components: 
Notice that this keepout currently works for planes but it is not yet working for traces.
Goal will be to expand this to support QFNs and other packages where we need to provide keepout functionality.
> Add Keepout Generators for SMT Components

- examples/landpatterns/app-specific-keepout.stanza
- src/landpatterns/keep-outs.stanza
This allows us to create keepouts outside of `pcb-component` definitions but have them track a particular instance in the layout. 
Example:
```
inst USBC : connectors/components/USB/USBTypeC/device
; Construct Pour Keepouts on applicable layers
val KO = KeepoutOverlay(Rectangle(3.0, 4.0))
make-keepout-overlay(
KO, USBC.J,
layer-set = [LayerIndex(0), LayerIndex(2), LayerIndex(3)]
name = "USBC-Keepout"
)
```
> Add App Specific Keepout Generator

- src/landpatterns/leads.stanza
- src/si/bus.stanza
This is a bit of a hack that is needed until we can address PROD-530
This allows SI topologies to properly construct constraints when using topo-bus.
> Pin Models for `topo-bus` instantiated components

- src/design/introspection.stanza
These tools are for constructing keepouts around components or parts of components, typically from a wrapping module.
> Added more functions for introspecting pads of a component

- src/design/introspection.stanza
- src/landpatterns/leads.stanza
- src/protocols/ethernet/MDI/MDI-1000Base-T.stanza
@tjknoth  - I address the issues you brought up with the `to-lp-pd-seq` function here.
> More Bug Fixes

- src/design/introspection.stanza
- src/landpatterns/thermal-vias.stanza
Remove get-connected-net
Also instantiate a new net in `make-thermal-vias` in order to eliminate any potential stabilization weirdness related to picking an arbitrary esir net.
> Prod 598 remove get connected net

- src/bundles/comms.stanza
- src/bundles/debug.stanza
- src/bundles/general.stanza
Current hypothesis is that this was causing confusion when debugging bundles because the bundle definition name was overriden with the `name` statement string.
I haven't changed the `protocols` bundles yet.
@bhusang  -  This might address the issues that we were encountering when debugging OCDB and JSL mixed definitions.
> [Refactor] Removed constant name statements on bundles

- src/geometry/box.stanza
- src/landpatterns/VirtualLP.stanza
- src/landpatterns/keep-outs.stanza
- src/landpatterns/silkscreen.stanza
A query error was selecting for super small components and resulted in exposing an error in the keepout logic - especially for components where the landpattern soldermask openings overlap. I've updated the logic to better handle that case as well as change the keepout interior pad boundary to use the copper shape instead of the soldermask.
> Keepout Box Bugfix

- src/circuits/ConfigStrap.stanza
This is a function for setting the BOM status of the components in the ConfigStrap object.
> Added a new tool for setting the config strap BOM status

- slm.toml
- src/circuits/ConfigStrap.stanza
I had used log2 instead of pow2 to compute the
max resulting in false positives in the
check.
> [Bugfix] Fixed check on config strap set value

- src/design.stanza
- src/design/Substrate.stanza
- src/layerstack.stanza
This adds a type for defining the PCB substrate in a consistent way that allows us to swap in and out different substrates as well. 
I tested this with the JLC library by having 7628 and 1080 versions, and then swapping between them.
> Add new `Substrate` type and `Layerstack` functions

- src/protocols/ethernet/MDI/MDI-1000Base-T.stanza
When attempting to create the supports for the KSZ9563 ethernet ports - I found that I needed more flexible control. I needed to construct a composite bundle that combined the MDI and the LED control pins.
By passing in a bundle argument, I can create this composite but still implement the MDI twisted
pair mappings.
> Updated the MDI 1000Base-T Supports Generators

- src/design/Substrate.stanza
PD crashes when the signal-boundary isn't set, so let's remove a footgun.
> Set signal boundary even if the shrink parameter isn't passed

- slm.toml
- src/design/Substrate.stanza
- src/geometry/basics.stanza
- src/landpatterns/BGA/pads.stanza
- src/landpatterns/leads/lead-profile.stanza
- src/landpatterns/pads.stanza
- src/landpatterns/thermal-pads.stanza
- src/landpatterns/two-pin/radial.stanza
Switches calls to the `expand(shape, amount)` function with calls to `expand-or-shrink(shape, amount)` instead. Note: this PR requires the PR in `jitx-client` of the same ticket to work.
> Jitx 9353/expand or shrink

- src/geometry/basics.stanza
- src/landpatterns/SOIC.stanza
- src/landpatterns/VirtualLP.stanza
- src/landpatterns/courtyard.stanza
- src/landpatterns/numbering.stanza
- src/landpatterns/package-body.stanza
- src/landpatterns/pad-planner.stanza
- src/landpatterns/pads.stanza
- src/landpatterns/silkscreen.stanza
Many changes here - most of them are going to support better handling of mounting holes.
> Updates to the non-plated hole and support for changes to `mechanical/MountingHoles`

- src/landpatterns/courtyard.stanza
- src/si/couplers.stanza
In the previous implementation 
```
inst tx-coupler : dp-coupler(
create-part(
mpn = "ESD132-B1-W0201 E6327", 
manufacturer = "Infineon"
)
)
```
Results in something like this:
because the parts-DB landpattern for this part is rotated 90 degrees from the JSL 2-pin standard landpattern.
This PR adds a new `pre-pose` argument that allows for the components in the `dp-coupler` to be oriented before being constructed in the coupler form. 
```
inst tx-coupler : dp-coupler(
create-part(
mpn = "ESD132-B1-W0201 E6327", 
manufacturer = "Infineon"
),
pre-pose = loc(0.0, 0.0, 90.0)
)
```
@Johnsel - FYI
> Update to `dp-coupler` for non-JSL 2-pin landpatterns

- examples/symbols/diode.stanza
- src/symbols/diodes.stanza
I've added a symbol generator for the TVS diode:
> Added TVS Diode Symbol

- examples/landpatterns/app-specific-keepout.stanza
- examples/landpatterns/board.stanza
Example of how it now shows the keepout region's effect:
> Updated app-specific keepout
